import { db } from '@/lib/db';
import Link from 'next/link';

export default async function Projects({ searchParams }: { searchParams: Promise<{ q?: string; category?: string }> }) {
  const params = await searchParams;
  const q = params.q?.trim() || '';
  const category = params.category?.trim() || '';
  const projects = await db.project.findMany({ where: { status:'OPEN', ...(category ? {category} : {}), ...(q ? { OR:[{title:{contains:q,mode:'insensitive'}},{description:{contains:q,mode:'insensitive'}},{category:{contains:q,mode:'insensitive'}}] } : {}) }, include:{owner:true}, orderBy:{createdAt:'desc'}, take:50 });
  const categories = await db.category.findMany({ orderBy:{name:'asc'}, take:30 });
  return <main className="container"><div className="page-heading"><div><span className="eyebrow">DISCOVERY</span><h1>Discover projects</h1><p className="muted">Search and filter live opportunities from the platform database.</p></div><Link href="/projects/new" className="btn primary">Create project</Link></div><form className="card" style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:10,marginBottom:22}}><input className="input" name="q" defaultValue={q} placeholder="Search projects, skills or categories…" /><select className="input" name="category" defaultValue={category}><option value="">All categories</option>{categories.map(c=><option value={c.name} key={c.id}>{c.name}</option>)}</select><button className="btn primary">Search</button></form><div className="stack">{projects.map(p=><article className="card" key={p.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><span className="badge">{p.category}</span><span className="muted">{p.location||'Remote'}</span></div><h2 style={{marginBottom:8}}>{p.title}</h2><p className="muted">{p.description}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'15px 0'}}>{p.skills.map(s=><span className="badge" key={s}>{s}</span>)}</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><span className="muted"><b>Owner:</b> {p.owner.name}{p.budget ? ` · GHS ${p.budget.toLocaleString()}` : ''}</span><Link href={`/projects/${p.id}`} className="btn primary">View project</Link></div></article>)}{!projects.length&&<div className="card empty"><h3>No matching projects</h3><p className="muted">Try a different search or category.</p></div>}</div></main>;
}
