'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function ProfilePage() {
  const router = useRouter();
  const [form, setForm] = useState({ name: '', email: '', bio: '', location: '', skills: '', categories: '', visibility: 'PUBLIC' });
  const [completion, setCompletion] = useState(0);
  const [status, setStatus] = useState('Loading profile…');
  useEffect(() => { fetch('/api/profile').then(r=>r.json()).then(d=>{ if(d.error){setStatus(d.error);return;} setForm({name:d.name,email:d.email,bio:d.bio,location:d.location,skills:d.skills.join(', '),categories:d.categories.join(', '),visibility:d.visibility}); setCompletion(d.completion); setStatus(''); }); }, []);
  async function save(e: FormEvent) { e.preventDefault(); setStatus('Saving…'); const res=await fetch('/api/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...form,skills:form.skills.split(',').map(x=>x.trim()).filter(Boolean),categories:form.categories.split(',').map(x=>x.trim()).filter(Boolean)})}); const data=await res.json(); if(!res.ok)return setStatus(data.error||'Could not save'); setCompletion(data.profile?.completion||0); setStatus('Profile saved successfully.'); router.refresh(); }
  return <main className="container narrow"><div className="page-heading"><div><span className="eyebrow">ACCOUNT</span><h1>Build your professional profile</h1><p className="muted">A complete profile improves discovery, trust and deterministic matching.</p></div><div className="card" style={{minWidth:180}}><span className="muted small">PROFILE COMPLETION</span><div className="stat">{completion}%</div><div style={{height:7,background:'#e5eaf2',borderRadius:99}}><div style={{height:7,width:`${completion}%`,background:'#2563eb',borderRadius:99}} /></div></div></div><form className="card form-card" onSubmit={save}><div className="form-grid"><label>Full name<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /></label><label>Email<input className="input" value={form.email} disabled /></label><label>Location<input className="input" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Accra, Ghana" /></label><label>Profile visibility<select className="input" value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="PUBLIC">Public</option><option value="PRIVATE">Private</option></select></label><label className="full">Bio<textarea className="input textarea" rows={6} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} placeholder="Tell people what you do, your strengths and the work you want to take on." /></label><label>Skills<input className="input" value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} placeholder="Research, Data, Design" /></label><label>Categories<input className="input" value={form.categories} onChange={e=>setForm({...form,categories:e.target.value})} placeholder="Professional Services, Technology" /></label></div><div className="form-actions"><button className="btn primary">Save profile</button>{status&&<span className="muted">{status}</span>}</div></form></main>;
}
